import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
 import { ThemeProvider } from "./providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ToDo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
   <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > 
            <main className="flex justify-end mx-10 my-3">
              <Nav />
            </main>
            {children}
           </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import {
//   ClerkProvider,
//   SignIn,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs'
// import Nav from "@/components/Nav";
// import { ThemeProvider } from "./providers/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ToDo",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body className={inter.className}>
//         <header className="flex justify-around">
          
//          <UserButton showName />
//         </header>
       
//       <SignedOut>
//           <SignIn routing="hash"/>
//         </SignedOut>
//       <SignedIn>
//       <ThemeProvider
//              attribute="class"
//              defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
      
//              <main className="flex justify-end mx-10 my-3">
//                <Nav />
//             </main>
//            {children}
//          </ThemeProvider>
        
//       </SignedIn>
        
//         </body>
//     </html>
//     </ClerkProvider>
//   );
// }


// import { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { ClerkProvider, SignIn, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
// import { ThemeProvider } from "./providers/theme-provider";
// import Nav from "@/components/Nav";

// const inter =  Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ToDo",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html>
//       <body className={inter.className}>
//     <ClerkProvider>
//       <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
//         <>
//           <header className="flex justify-around">
//             <h1>Alphazero</h1>
//             <UserButton showName />
//           </header>

//           <SignedOut>
//             <SignIn routing="hash" />
//           </SignedOut>

//           <SignedIn>
//             <div className={inter.className}>
//               <main className="flex justify-end mx-10 my-3">
//                 <Nav />
//               </main>
//               {children}
//             </div>
//           </SignedIn>
//         </>
//       </ThemeProvider>
//     </ClerkProvider>
//     </body>
//     </html>
//   );
// }



